on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Node CI

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['10.x', '12.x', '13.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v1
        id: node-cache
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
      - name: Build
        run: npm ci
        # if: steps.node-cache.outputs.cache-hit != 'true'
      - name: Test
        run: npm test
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        uses: stoe/xo-action@c7b6b32
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
